#!/bin/bash

if [ ! -e "/usr/local/share/NHIICC/mLNHIICC" ] ; then
    mkdir -p /usr/local/share/NHIICC
    chmod 755 /usr/local/share/NHIICC
    case $(uname -m) in
    x86_64)
        cp ./x64/mLNHIICC /usr/local/share/NHIICC/mLNHIICC
        echo "x86_64"
        ;;
    i*86)
        cp ./x32/mLNHIICC /usr/local/share/NHIICC/mLNHIICC
        echo "32 bit version"
        ;;
    *)
        echo "unknow OS bits , Sorry! No support!"
        exit 0
        ;;
    esac

    chmod 755 /usr/local/share/NHIICC/mLNHIICC
    cp -R ./html /usr/local/share/NHIICC
    cp -R ./cert /usr/local/share/NHIICC

    grep -q iccert.nhi.gov.tw /etc/hosts | grep -q 127.0.0.1
    if [ ! $? -eq 0 ]
    then
        echo 127.0.0.1 iccert.nhi.gov.tw >> /etc/hosts
    fi

    certfile="./cert/NHIRootCA.crt"
    certname="NHI SelfRoot CA"
    certfile2="./cert/NHIServerCert.crt"
    certname2="NHI Self Sign Server"

    for certDB in $(find ~/ -name "cert8.db")
    do
        certdir=$(dirname ${certDB});
        certutil -A -n "${certname}" -t "TCu,Cu,Tu" -i ${certfile} -d dbm:${certdir}
        certutil -A -n "${certname2}" -t "P,," -i ${certfile2} -d dbm:${certdir}
    done

    for certDB in $(find ~/ -name "cert9.db")
    do
        certdir=$(dirname ${certDB});
        certutil -A -n "${certname}" -t "TCu,Cu,Tu" -i ${certfile} -d sql:${certdir}
        certutil -A -n "${certname2}" -t "P,," -i ${certfile2} -d sql:${certdir}
    done
fi

if [ -f /etc/arch-release ]; then
    which pacman && {
       pacman --needed -S glibc pcsclite openssl-1.0 ca-certificates
    }

    update-ca-trust force-enable
    cp ./cert/NHIServerCert.crt /etc/ca-certificates/trust-source/anchors/
    update-ca-trust extract

    cp ./NHIICC.service /etc/systemd/system/
    chmod 664 /etc/systemd/system/NHIICC.service
fi
