#!/bin/bash

grep -q iccert.nhi.gov.tw /etc/hosts;
if [ $? -eq 0 ] ; then
    sed -i '/iccert\.nhi\.gov\.tw/d' /etc/hosts
fi

if [ -f '/etc/systemd/system/NHIICC.service' ]; then
    systemctl stop NHIICC
    rm /etc/systemd/system/NHIICC.service
fi

if [ -d /usr/local/share/NHIICC ]; then
    rm -R /usr/local/share/NHIICC
fi

certfile="./cert/NHIRootCA.crt"
certname="NHI Self Root CA"
certfile2="./cert/NHIServerCert.crt"
certname2="NHI Self Sign Server"

for certDB in $(find ~/ -name "cert8.db")
do
    certdir=$(dirname ${certDB});
    certutil -D -n "${certname}" -d dbm:${certdir}
    certutil -D -n "${certname2}" -d dbm:${certdir}
done

for certDB in $(find ~/ -name "cert9.db")
do
    certdir=$(dirname ${certDB});
    certutil -D -n "${certname}" -d sql:${certdir}
    certutil -D -n "${certname2}" -d sql:${certdir}
done
